version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database-ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=ignite-api
    volumes:
      - pgdata:/data/postgres    

  app:
    build: .
    container_name: ignite-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app        


volumes:
  pgdata:
    driver: local

